steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
      architecture: "$(architecture)"
      allowUnstable: "$(allowUnstable)"
    displayName: "Use Python $(python.version) $(architecture)"
